import { useState, useEffect, useCallback } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { MainLayout } from "@/layouts/MainLayout";
import { DottedGrid } from "@/components/canvas/DottedGrid";
import { ExistingModels } from "@/components/canvas/ExistingModels";
import { ActionButtons } from "@/components/canvas/ActionButtons";
import { PatientSearch } from "@/components/canvas/PatientSearch";
import { EHRDisplay } from "@/components/canvas/EHRDisplay";
import { DrugModelSelector } from "@/components/canvas/DrugModelSelector";
import { AnalysisResults } from "@/components/canvas/AnalysisResults";
import { AmbientBackground } from "@/components/AmbientBackground";
import { ThreeBackground } from "@/components/ThreeBackground";
// Research components
import { ResearchPrompt } from "@/components/research/ResearchPrompt";
import { ActiveThesisBar } from "@/components/research/ActiveThesisBar";
import { AgentTimeline } from "@/components/research/AgentTimeline";
import { ResearchCandidateSelector } from "@/components/research/ResearchCandidateSelector";
import { SkeletonDashboard } from "@/components/research/SkeletonDashboard";
import { CodeEditor } from "@/components/research/CodeEditor";
import { DataDropZone } from "@/components/research/DataDropZone";
import { ResultsDashboard } from "@/components/research/ResultsDashboard";
import { RoadmapStubs } from "@/components/research/RoadmapStubs";

import { supabase } from "@/integrations/supabase/client";
import { Loader2, ArrowLeft } from "lucide-react";

type CanvasState = 
  | "idle" 
  | "patient-search"
  | "ehr-loading"
  | "ehr-display"
  | "drug-selection"
  | "analysis-results"
  // Research states
  | "research-prompt"
  | "research-generating"      // Stage 1: Agent 1 generates candidates
  | "research-candidate-select" // User selects from 3 candidates
  | "research-processing"       // Stage 2: Agent 2 processes selection
  | "research-code-ready"
  | "research-awaiting-data"
  | "research-results";

interface Patient {
  id: string;
  name: string;
  dob: string;
  gender: string;
  mrn: string;
}

interface AgentStep {
  id: string;
  agent: string;
  status: "pending" | "active" | "complete";
  message: string;
}

// Multi-agent steps for Research workflow
const AGENT_STEPS: AgentStep[] = [
  { id: "1", agent: "Agent 1", status: "pending", message: "Parsing research question & generating candidates..." },
  { id: "2a", agent: "Agent 2a", status: "pending", message: "Extracting causal structure from selection..." },
  { id: "2b", agent: "Agent 2b", status: "pending", message: "Validating confounders & building DAG..." },
  { id: "3", agent: "Agent 3", status: "pending", message: "Generating target trial emulation script..." },
];

const SAMPLE_CODE = `# Verified Causal Analysis Script
# Optimized for NIH All of Us (AoU) Environment
# Generated by Agent 3 | Confidence: 98.7%

import pandas as pd
from causalinference import CausalModel
from sklearn.preprocessing import StandardScaler

def run_target_trial_emulation(cohort_data: pd.DataFrame) -> dict:
    """
    Emulates a target trial for drug efficacy analysis.
    """
    treatment_col = 'drug_exposure'
    outcome_col = 'clinical_outcome'
    
    covariates = [
        'age', 'sex', 'bmi', 'comorbidity_index',
        'prior_medications', 'genetic_risk_score'
    ]
    
    scaler = StandardScaler()
    X = scaler.fit_transform(cohort_data[covariates])
    
    model = CausalModel(
        Y=cohort_data[outcome_col].values,
        D=cohort_data[treatment_col].values,
        X=X
    )
    
    model.est_propensity_s()
    model.trim_s()
    model.stratify_s()
    model.est_via_matching(bias_adj=True)
    
    return {
        'ate': model.estimates['matching']['ate'],
        'ate_se': model.estimates['matching']['ate_se'],
        'n_treated': model.summary_stats['N_t'],
        'n_control': model.summary_stats['N_c'],
        'confidence_interval': model.estimates['matching']['ate_ci']
    }

if __name__ == "__main__":
    cohort = pd.read_csv('aou_cohort_export.csv')
    results = run_target_trial_emulation(cohort)
    print(f"Average Treatment Effect: {results['ate']:.4f}")
    print(f"95% CI: {results['confidence_interval']}")
`;

// Mock data
const mockModels = [
  { id: "1", name: "Image Classification v2", status: "completed" as const, timestamp: "2 hours ago" },
  { id: "2", name: "Sentiment Analyzer", status: "running" as const, timestamp: "1 day ago" },
  { id: "3", name: "Object Detection", status: "completed" as const, timestamp: "3 days ago" },
];

const Canvas = () => {
  const [hasExistingModels] = useState(false);
  const [canvasState, setCanvasState] = useState<CanvasState>("idle");
  const [buttonsAnimated, setButtonsAnimated] = useState(false);
  
  // Patient analysis state
  const [selectedPatient, setSelectedPatient] = useState<Patient | null>(null);
  const [ehrData, setEhrData] = useState<any>(null);
  const [analysisResult, setAnalysisResult] = useState<any>(null);

  // Research state
  const [thesis, setThesis] = useState("");
  const [agentSteps, setAgentSteps] = useState<AgentStep[]>(AGENT_STEPS);
  const [researchResultsData, setResearchResultsData] = useState<any>(null);

  useEffect(() => {
    if (!hasExistingModels && canvasState === "idle" && !buttonsAnimated) {
      const timer = setTimeout(() => {
        setButtonsAnimated(true);
      }, 800);
      return () => clearTimeout(timer);
    }
  }, [hasExistingModels, canvasState, buttonsAnimated]);

  // Listen for nav-reset event to return to idle
  useEffect(() => {
    const handleNavReset = (e: CustomEvent) => {
      if (e.detail.path === '/research') {
        resetToIdle();
      }
    };

    window.addEventListener('nav-reset', handleNavReset as EventListener);
    return () => window.removeEventListener('nav-reset', handleNavReset as EventListener);
  }, []);

  const handlePatientAnalysis = () => {
    setCanvasState("patient-search");
    setSelectedPatient(null);
    setEhrData(null);
    setAnalysisResult(null);
  };

  const handleResearch = () => {
    setCanvasState("research-prompt");
    setThesis("");
    setAgentSteps(AGENT_STEPS);
    setResearchResultsData(null);
  };

  const handlePatientSelect = async (patient: Patient) => {
    setSelectedPatient(patient);
    setCanvasState("ehr-loading");

    try {
      const { data, error } = await supabase.functions.invoke('epic-ehr', {
        body: { action: 'getEHR', patientId: patient.id },
      });

      if (error) throw error;
      setEhrData(data.ehr);
      setCanvasState("ehr-display");
    } catch (err) {
      console.error('Failed to load EHR:', err);
      setCanvasState("patient-search");
    }
  };

  const handleAnalysisComplete = (drugs: string[], modelId: string, result: any) => {
    setAnalysisResult(result);
    setCanvasState("analysis-results");
  };

  // Research handlers
  // Stage 1: When user submits prompt, Agent 1 starts generating candidates
  const handleResearchPromptSubmit = useCallback((prompt: string) => {
    setThesis(prompt);
    setCanvasState("research-generating");
    
    // Agent 1 becomes active immediately
    setAgentSteps(prev => prev.map((step, i) => ({
      ...step,
      status: i === 0 ? "active" : "pending"
    })));
    
    // After a brief delay, Agent 1 completes and show candidates
    setTimeout(() => {
      setAgentSteps(prev => prev.map((step, i) => ({
        ...step,
        status: i === 0 ? "complete" : "pending"
      })));
      setCanvasState("research-candidate-select");
    }, 2500);
  }, []);

  // Stage 2: When user selects a candidate, Agents 2a, 2b, 3 run sequentially
  const handleCandidateSelect = useCallback((selectedQuestion: string) => {
    setThesis(selectedQuestion);
    setCanvasState("research-processing");
    
    // Agent 2a becomes active
    setAgentSteps(prev => prev.map((step, i) => ({
      ...step,
      status: i === 0 ? "complete" : i === 1 ? "active" : "pending"
    })));
    
    // After 1.5s, Agent 2a completes, Agent 2b starts
    setTimeout(() => {
      setAgentSteps(prev => prev.map((step, i) => ({
        ...step,
        status: i <= 1 ? "complete" : i === 2 ? "active" : "pending"
      })));
    }, 1500);
    
    // After 3s, Agent 2b completes, Agent 3 starts
    setTimeout(() => {
      setAgentSteps(prev => prev.map((step, i) => ({
        ...step,
        status: i <= 2 ? "complete" : i === 3 ? "active" : "pending"
      })));
    }, 3000);
    
    // After 5s, all agents complete
    setTimeout(() => {
      setAgentSteps(prev => prev.map(step => ({
        ...step,
        status: "complete"
      })));
      setCanvasState("research-code-ready");
    }, 5000);
  }, []);

  const handleCodeCopied = useCallback(() => {
    setTimeout(() => {
      setCanvasState("research-awaiting-data");
    }, 1000);
  }, []);

  const handleDataDrop = useCallback((data: any) => {
    setResearchResultsData(data);
    setCanvasState("research-results");
  }, []);

  const handleResearchReset = useCallback(() => {
    setCanvasState("research-prompt");
    setThesis("");
    setAgentSteps(AGENT_STEPS);
    setResearchResultsData(null);
  }, []);

  const resetToIdle = () => {
    setCanvasState("idle");
    setSelectedPatient(null);
    setEhrData(null);
    setAnalysisResult(null);
    setThesis("");
    setAgentSteps(AGENT_STEPS);
    setResearchResultsData(null);
    setButtonsAnimated(true);
  };

  const showBackButton = canvasState !== "idle";
  const isResearchState = canvasState.startsWith("research-");
  // Show agent timeline during generating or processing phases
  const showAgentTimeline = canvasState === "research-generating" || 
                            canvasState === "research-candidate-select" || 
                            canvasState === "research-processing";
  
  // Map canvas state to research phase for ActiveThesisBar
  const getResearchPhase = (): "prompt" | "processing" | "code-ready" | "awaiting-data" | "results" | null => {
    if (!isResearchState) return null;
    if (canvasState === "research-generating" || canvasState === "research-candidate-select") return "processing";
    return canvasState.replace("research-", "") as any;
  };
  const researchPhase = getResearchPhase();

  return (
    <MainLayout showFooter={false}>
      <div className="relative h-[calc(100vh-4rem)] overflow-hidden bg-background">
        <AmbientBackground />
        <ThreeBackground />
        <DottedGrid />

        {/* Back button - fixed position below navbar */}
        <AnimatePresence>
          {showBackButton && (
            <motion.button
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -20 }}
              transition={{ duration: 0.2 }}
              onClick={resetToIdle}
              className="fixed top-20 left-6 z-50 flex items-center gap-2 px-3 py-2 rounded-lg
                         bg-background/60 backdrop-blur-sm border border-border/50
                         text-muted-foreground hover:text-foreground hover:bg-background/80
                         transition-colors"
            >
              <ArrowLeft className="w-4 h-4" />
              <span className="text-sm font-medium">Back</span>
            </motion.button>
          )}
        </AnimatePresence>

        <div className="relative z-10 h-full flex">
          {/* Left sidebar - Agent Timeline (visible during research generating/processing) */}
          <AnimatePresence>
            {showAgentTimeline && <AgentTimeline steps={agentSteps} />}
          </AnimatePresence>

          {/* Main content area */}
          <div className="flex-1 flex flex-col">
            {/* Active Thesis Bar (visible during research after prompt submission) */}
            <AnimatePresence>
              {isResearchState && canvasState !== "research-prompt" && (
                <ActiveThesisBar thesis={thesis} phase={researchPhase!} onReset={handleResearchReset} />
              )}
            </AnimatePresence>

            {/* Central content */}
            <div className="flex-1 flex items-center justify-center px-6 overflow-y-auto">
              <AnimatePresence mode="wait">
                {hasExistingModels ? (
                  <ExistingModels key="existing" models={mockModels} />
                ) : (
                  <>
                    {/* Patient Analysis States */}
                    {canvasState === "patient-search" && (
                      <PatientSearch
                        key="patient-search"
                        onPatientSelect={handlePatientSelect}
                      />
                    )}

                    {canvasState === "ehr-loading" && (
                      <motion.div
                        key="ehr-loading"
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        exit={{ opacity: 0 }}
                        className="text-center"
                      >
                        <Loader2 className="w-10 h-10 animate-spin text-primary mx-auto mb-4" />
                        <p className="text-muted-foreground">Loading patient EHR from Epic...</p>
                      </motion.div>
                    )}

                    {canvasState === "ehr-display" && selectedPatient && ehrData && (
                      <EHRDisplay
                        key="ehr-display"
                        patient={selectedPatient}
                        ehrData={ehrData}
                        onBack={() => setCanvasState("patient-search")}
                        onProceed={() => setCanvasState("drug-selection")}
                      />
                    )}

                    {canvasState === "drug-selection" && selectedPatient && ehrData && (
                      <DrugModelSelector
                        key="drug-selection"
                        patient={selectedPatient}
                        ehrData={ehrData}
                        onBack={() => setCanvasState("ehr-display")}
                        onRunAnalysis={handleAnalysisComplete}
                      />
                    )}

                    {canvasState === "analysis-results" && selectedPatient && analysisResult && (
                      <AnalysisResults
                        key="analysis-results"
                        result={analysisResult}
                        patient={selectedPatient}
                        onNewAnalysis={() => setCanvasState("drug-selection")}
                        onBackToSearch={resetToIdle}
                      />
                    )}

                    {/* Research States */}
                    {canvasState === "research-prompt" && (
                      <ResearchPrompt key="research-prompt" onSubmit={handleResearchPromptSubmit} />
                    )}

                    {canvasState === "research-generating" && (
                      <SkeletonDashboard key="research-generating" />
                    )}

                    {canvasState === "research-candidate-select" && (
                      <ResearchCandidateSelector
                        key="research-candidates"
                        onSelect={handleCandidateSelect}
                        onBack={() => setCanvasState("research-prompt")}
                      />
                    )}

                    {canvasState === "research-processing" && (
                      <SkeletonDashboard key="research-processing" />
                    )}

                    {canvasState === "research-code-ready" && (
                      <CodeEditor key="research-code" code={SAMPLE_CODE} onCopied={handleCodeCopied} />
                    )}

                    {canvasState === "research-awaiting-data" && (
                      <DataDropZone key="research-dropzone" onDataDrop={handleDataDrop} />
                    )}

                    {canvasState === "research-results" && (
                      <ResultsDashboard key="research-results" data={researchResultsData} />
                    )}

                    {/* Idle State */}
                    {canvasState === "idle" && (
                      <motion.div
                        key="welcome"
                        className="text-center"
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        exit={{ opacity: 0, y: -20 }}
                        transition={{ duration: 0.5 }}
                      >
                        <h2 className="font-display text-2xl font-medium text-foreground mb-3">
                          Ready to build
                        </h2>
                        <p className="text-muted-foreground mb-8">
                          Click "Research" to start causal analysis or "Patient Analysis" for EHR-based drug modeling
                        </p>
                        
                        <motion.div
                          initial={{ opacity: 0, y: 10 }}
                          animate={{ opacity: 1, y: 0 }}
                          transition={{ duration: 0.4, delay: 0.2 }}
                        >
                          <ActionButtons
                            isAnimating={buttonsAnimated}
                            onPatientAnalysis={handlePatientAnalysis}
                            onResearch={handleResearch}
                          />
                        </motion.div>
                      </motion.div>
                    )}
                  </>
                )}
              </AnimatePresence>
            </div>

            {/* Future Roadmap Stubs for Research */}
            {canvasState === "research-results" && <RoadmapStubs />}
          </div>
        </div>
      </div>
    </MainLayout>
  );
};

export default Canvas;
