import { useState, useCallback } from "react";
import { AnimatePresence } from "framer-motion";
import { MainLayout } from "@/layouts/MainLayout";
import { DottedGrid } from "@/components/canvas/DottedGrid";
import { ResearchPrompt } from "@/components/research/ResearchPrompt";
import { ActiveThesisBar } from "@/components/research/ActiveThesisBar";
import { AgentTimeline } from "@/components/research/AgentTimeline";
import { SkeletonDashboard } from "@/components/research/SkeletonDashboard";
import { CodeEditor } from "@/components/research/CodeEditor";
import { DataDropZone } from "@/components/research/DataDropZone";
import { ResultsDashboard } from "@/components/research/ResultsDashboard";
import { RoadmapStubs } from "@/components/research/RoadmapStubs";

export type ResearchPhase = 
  | "prompt" 
  | "processing" 
  | "code-ready" 
  | "awaiting-data" 
  | "results";

export interface AgentStep {
  id: string;
  agent: string;
  status: "pending" | "active" | "complete";
  message: string;
}

const AGENT_STEPS: AgentStep[] = [
  { id: "1", agent: "Agent 1", status: "pending", message: "Emulating Target Trial Parameters..." },
  { id: "2a", agent: "Agent 2a", status: "pending", message: "Parsing intervention specifications..." },
  { id: "2b", agent: "Agent 2b", status: "pending", message: "Cross-referencing SOTA stack..." },
  { id: "3", agent: "Agent 3", status: "pending", message: "Generating verified causal script..." },
];

const SAMPLE_CODE = `# Verified Causal Analysis Script
# Optimized for NIH All of Us (AoU) Environment
# Generated by Agent 3 | Confidence: 98.7%

import pandas as pd
from causalinference import CausalModel
from sklearn.preprocessing import StandardScaler

def run_target_trial_emulation(cohort_data: pd.DataFrame) -> dict:
    """
    Emulates a target trial for drug efficacy analysis.
    
    Args:
        cohort_data: Patient cohort from AoU Researcher Workbench
    
    Returns:
        dict: Causal effect estimates with confidence intervals
    """
    
    # Define treatment and outcome variables
    treatment_col = 'drug_exposure'
    outcome_col = 'clinical_outcome'
    
    # Covariates for propensity score matching
    covariates = [
        'age', 'sex', 'bmi', 'comorbidity_index',
        'prior_medications', 'genetic_risk_score'
    ]
    
    # Standardize continuous variables
    scaler = StandardScaler()
    X = scaler.fit_transform(cohort_data[covariates])
    
    # Initialize causal model
    model = CausalModel(
        Y=cohort_data[outcome_col].values,
        D=cohort_data[treatment_col].values,
        X=X
    )
    
    # Estimate propensity scores
    model.est_propensity_s()
    
    # Trim non-overlap regions
    model.trim_s()
    
    # Stratify on propensity score
    model.stratify_s()
    
    # Estimate treatment effects
    model.est_via_matching(bias_adj=True)
    
    return {
        'ate': model.estimates['matching']['ate'],
        'ate_se': model.estimates['matching']['ate_se'],
        'n_treated': model.summary_stats['N_t'],
        'n_control': model.summary_stats['N_c'],
        'confidence_interval': model.estimates['matching']['ate_ci']
    }

if __name__ == "__main__":
    # Load cohort from AoU export
    cohort = pd.read_csv('aou_cohort_export.csv')
    
    results = run_target_trial_emulation(cohort)
    
    print(f"Average Treatment Effect: {results['ate']:.4f}")
    print(f"95% CI: {results['confidence_interval']}")
`;

const Research = () => {
  const [phase, setPhase] = useState<ResearchPhase>("prompt");
  const [thesis, setThesis] = useState("");
  const [agentSteps, setAgentSteps] = useState<AgentStep[]>(AGENT_STEPS);
  const [resultsData, setResultsData] = useState<any>(null);

  const handlePromptSubmit = useCallback((prompt: string) => {
    setThesis(prompt);
    setPhase("processing");
    
    // Simulate agent progression
    const stepDelays = [500, 1500, 3000, 4500];
    const completeDelays = [1400, 2900, 4400, 6000];
    
    stepDelays.forEach((delay, index) => {
      setTimeout(() => {
        setAgentSteps(prev => prev.map((step, i) => ({
          ...step,
          status: i === index ? "active" : i < index ? "complete" : "pending"
        })));
      }, delay);
    });
    
    completeDelays.forEach((delay, index) => {
      setTimeout(() => {
        setAgentSteps(prev => prev.map((step, i) => ({
          ...step,
          status: i <= index ? "complete" : step.status
        })));
      }, delay);
    });
    
    // Transition to code-ready after all agents complete
    setTimeout(() => {
      setPhase("code-ready");
    }, 6500);
  }, []);

  const handleCodeCopied = useCallback(() => {
    // After copying, transition to awaiting data
    setTimeout(() => {
      setPhase("awaiting-data");
    }, 1000);
  }, []);

  const handleDataDrop = useCallback((data: any) => {
    setResultsData(data);
    setPhase("results");
  }, []);

  const handleReset = useCallback(() => {
    setPhase("prompt");
    setThesis("");
    setAgentSteps(AGENT_STEPS);
    setResultsData(null);
  }, []);

  return (
    <MainLayout showFooter={false}>
      <div className="relative h-[calc(100vh-4rem)] overflow-hidden bg-background">
        <DottedGrid />

        <div className="relative z-10 h-full flex">
          {/* Left sidebar - Agent Timeline (visible during processing) */}
          <AnimatePresence>
            {phase === "processing" && <AgentTimeline steps={agentSteps} />}
          </AnimatePresence>

          {/* Main content area */}
          <div className="flex-1 flex flex-col">
            {/* Active Thesis Bar (visible after prompt submission) */}
            <AnimatePresence>
              {phase !== "prompt" && (
                <ActiveThesisBar thesis={thesis} phase={phase} onReset={handleReset} />
              )}
            </AnimatePresence>

            {/* Central content */}
            <div className="flex-1 flex items-center justify-center p-6">
              <AnimatePresence mode="wait">
                {phase === "prompt" && (
                  <ResearchPrompt key="prompt" onSubmit={handlePromptSubmit} />
                )}

                {phase === "processing" && (
                  <SkeletonDashboard key="skeleton" />
                )}

                {phase === "code-ready" && (
                  <CodeEditor key="code" code={SAMPLE_CODE} onCopied={handleCodeCopied} />
                )}

                {phase === "awaiting-data" && (
                  <DataDropZone key="dropzone" onDataDrop={handleDataDrop} />
                )}

                {phase === "results" && (
                  <ResultsDashboard key="results" data={resultsData} />
                )}
              </AnimatePresence>
            </div>

            {/* Future Roadmap Stubs */}
            {phase === "results" && <RoadmapStubs />}
          </div>
        </div>
      </div>
    </MainLayout>
  );
};

export default Research;
